import { tool } from '@opencode-ai/plugin';
import { ForLoopAPIClient } from '../capabilities/api-client';
import { resolveSprintId } from '../capabilities/context-resolver';
import { validateToken } from '../capabilities/auth';

export function createAgentSuggestTool(client: ForLoopAPIClient) {
  return tool({
    description: 'Get AI suggestions for story breakdowns, estimates, and planning',
    args: {
      type: tool.schema.enum([
        'breakdown',
        'estimate',
        'acceptance_criteria',
        'test_cases',
        'related',
        'sprint_planning',
      ]).describe('Type of suggestion needed'),
      sprintId: tool.schema.number()
        .optional()
        .describe('Sprint ID for context'),
      storyId: tool.schema.number()
        .optional()
        .describe('Story ID to analyze'),
      query: tool.schema.string()
        .optional()
        .describe('Specific question or requirement'),
    },
    async execute(args, _context) {
      const tokenResult = await validateToken();
      if (!tokenResult.valid) {
        return tokenResult.error;
      }
      client.setToken?.(tokenResult.token);

      if (!args.sprintId && !args.storyId) {
        return [
          '❌ Please provide sprintId or storyId',
          '',
          'Examples:',
          '  forloop.agent.suggest --type breakdown --sprintId 123',
          '  forloop.agent.suggest --type estimate --storyId 456',
        ].join('\n');
      }

      try {
        const response = await client.getAgentSuggestions({
          sprintId: args.sprintId,
          storyId: args.storyId,
          type: args.type,
          query: args.query,
        });

        const lines = [
          `🤖 AI Suggestions (${response.agentKey})`,
          `Confidence: ${(response.confidence * 100).toFixed(0)}%`,
          '',
          '**Suggestions:**',
          '',
        ];

        for (const suggestion of response.suggestions) {
          lines.push(`- ${suggestion}`);
        }

        return lines.join('\n');
      } catch (error: any) {
        return `❌ Error: ${error.message}`;
      }
    },
  });
}

export function createStoryBreakdownTool(client: ForLoopAPIClient) {
  return tool({
    description: 'Break down a story into actionable subtasks',
    args: {
      storyId: tool.schema.number()
        .describe('Story ID to break down'),
    },
    async execute(args, _context) {
      const tokenResult = await validateToken();
      if (!tokenResult.valid) {
        return tokenResult.error;
      }
      client.setToken?.(tokenResult.token);

      try {
        const breakdown = await client.getStoryBreakdown(args.storyId);

        const lines = [
          `📋 Story Breakdown: #${breakdown.storyId}`,
          `**${breakdown.title}**`,
          '',
          '**Subtasks to consider:**',
          '',
        ];

        for (let i = 0; i < breakdown.breakdown.length; i++) {
          lines.push(`${i + 1}. ${breakdown.breakdown[i]}`);
        }

        lines.push('');
        lines.push(`💡 Generated by ${breakdown.agentKey}`);

        return lines.join('\n');
      } catch (error: any) {
        return `❌ Error: ${error.message}`;
      }
    },
  });
}

export function createStoryEstimateTool(client: ForLoopAPIClient) {
  return tool({
    description: 'Get AI-powered story point estimates',
    args: {
      storyId: tool.schema.number()
        .describe('Story ID to estimate'),
    },
    async execute(args, _context) {
      const tokenResult = await validateToken();
      if (!tokenResult.valid) {
        return tokenResult.error;
      }
      client.setToken?.(tokenResult.token);

      try {
        const estimate = await client.getStoryEstimate(args.storyId);

        const lines = [
          `⏱️ Story Estimate: #${estimate.storyId}`,
          `**${estimate.title}**`,
          '',
          `Current Points: ${estimate.currentPoints || 'Not set'}`,
          `Suggested Points: ${estimate.suggestedPoints}`,
          '',
          '**Estimation rationale:**',
          '',
        ];

        for (const item of estimate.estimates) {
          lines.push(`- ${item}`);
        }

        return lines.join('\n');
      } catch (error: any) {
        return `❌ Error: ${error.message}`;
      }
    },
  });
}

export function createConversationHistoryTool(client: ForLoopAPIClient) {
  return tool({
    description: 'View conversation history with AI agents from opencode sessions',
    args: {
      sprintId: tool.schema.number()
        .optional()
        .describe('Filter by sprint'),
      limit: tool.schema.number()
        .min(1)
        .max(200)
        .default(50)
        .describe('Number of messages to retrieve'),
    },
    async execute(args, context) {
      const tokenResult = await validateToken();
      if (!tokenResult.valid) {
        return tokenResult.error;
      }
      client.setToken?.(tokenResult.token);

      const resolution = await resolveSprintId(args.sprintId, context.directory);
      const sprintId = resolution.sprintId || args.sprintId;

      try {
        const history = await client.getConversationHistory({
          sprintId,
          limit: args.limit,
        });

        const messages = history.messages || [];
        if (messages.length === 0) {
          return 'No conversation history found.';
        }

        const lines = [
          `💬 Conversation History (${history.total || messages.length} total)`,
          '',
        ];

        for (const msg of messages.slice(0, args.limit)) {
          const preview = (msg.userMessage || 'No message').substring(0, 80);
          const hasResponse = msg.agentResponse && msg.agentResponse.trim();

          lines.push(`📌 **${preview}**${preview.length >= 80 ? '...' : ''}`);

          if (msg.conversationId) {
            const agentMatch = msg.conversationId.match(/agent:([^:]+)/);
            if (agentMatch) {
              lines.push(`   Agent: ${agentMatch[1]} | ${formatDate(msg.timestamp)}`);
            } else {
              lines.push(`   ${formatDate(msg.timestamp)}`);
            }
          } else {
            lines.push(`   ${formatDate(msg.timestamp)}`);
          }

          if (hasResponse) {
            const respPreview = msg.agentResponse.substring(0, 100);
            lines.push(`   → ${respPreview}${msg.agentResponse.length > 100 ? '...' : ''}`);
          }

          lines.push('');
        }

        return lines.join('\n');
      } catch (error: any) {
        return `❌ Error: ${error.message}`;
      }
    },
  });
}

export function createClearHistoryTool(client: ForLoopAPIClient) {
  return tool({
    description: 'Clear opencode conversation history for a sprint',
    args: {
      sprintId: tool.schema.number()
        .optional()
        .describe('Clear only for specific sprint'),
      confirm: tool.schema.boolean()
        .default(false)
        .describe('Confirm deletion'),
    },
    async execute(args, context) {
      const tokenResult = await validateToken();
      if (!tokenResult.valid) {
        return tokenResult.error;
      }
      client.setToken?.(tokenResult.token);

      if (!args.confirm) {
        return [
          '⚠️ Warning: This will permanently delete conversation history.',
          '',
          'Use --confirm true to proceed.',
          'Or specify --sprintId to delete only for a specific sprint.',
        ].join('\n');
      }

      const resolution = await resolveSprintId(args.sprintId, context.directory);
      const sprintId = resolution.sprintId || args.sprintId;

      try {
        const result = await client.clearConversationHistory({
          sprintId,
        });

        return `✅ Deleted ${result.count} messages successfully.`;
      } catch (error: any) {
        return `❌ Error: ${error.message}`;
      }
    },
  });
}

function formatDate(dateString: string): string {
  return new Date(dateString).toLocaleDateString('en-US', {
    month: 'short',
    day: 'numeric',
    hour: '2-digit',
    minute: '2-digit',
  });
}
